import type { Metadata } from "next"
import { LegalDocument } from "@/components/home/legal-document"
import { getPublicSettings } from "@/lib/services/settings"
import {
    buildShareMetadata,
    getPublicBrandMeta,
} from "@/lib/public-metadata"

export async function generateMetadata(): Promise<Metadata> {
    const { title: siteTitle, baseUrl } = await getPublicBrandMeta()
    const pageTitle = "Privacy Policy"
    const description = `Privacy Policy for ${siteTitle}`
    const share = buildShareMetadata({
        title: `${pageTitle} | ${siteTitle}`,
        description,
        siteName: siteTitle,
        url: baseUrl ? `${baseUrl}/privacy` : undefined,
        imageAlt: `${siteTitle} Privacy Policy`,
    })

    return {
        title: pageTitle,
        description,
        ...share,
        robots: { index: true, follow: true },
    }
}

export default async function PrivacyPage() {
    const settings = await getPublicSettings()
    const siteTitle = settings?.site_title || "EmailJachai Pro"
    const logoUrl = settings?.logo_url || settings?.favicon_url || "/logo.svg"

    return (
        <LegalDocument
            siteTitle={siteTitle}
            logoUrl={logoUrl}
            twitterUrl={settings?.twitter_url}
            linkedinUrl={settings?.linkedin_url}
            youtubeUrl={settings?.youtube_url}
            facebookUrl={settings?.facebook_url}
            title="Privacy Policy"
            updatedAt="July 31, 2026"
            intro={`This Privacy Policy explains how ${siteTitle} ("we", "us") collects, uses, and protects information when you use our website and email verification Service.`}
            sections={[
                {
                    title: "Information We Collect",
                    paragraphs: [
                        "Account information: such as name, email address, password (stored hashed), and billing-related details needed to provide credits or licenses.",
                        "Service data: email addresses and files you submit for verification, job metadata, API usage, and verification results generated by the Service.",
                        "Technical data: IP address, browser type, device information, approximate location derived from IP, cookies or similar technologies, and logs used for security and reliability.",
                    ],
                },
                {
                    title: "How We Use Information",
                    paragraphs: [
                        "We use information to provide and improve verification, operate accounts, process payments, prevent fraud and abuse, send transactional messages (such as receipts or security alerts), and comply with legal obligations.",
                        "We may use aggregated or anonymized statistics to understand product performance. We do not sell your personal information.",
                    ],
                },
                {
                    title: "Email Lists You Upload",
                    paragraphs: [
                        "Emails you upload are processed to run verification checks and return results to you. You are responsible for ensuring you have a lawful basis to process those addresses.",
                        "We retain submitted list data and results as needed to deliver the Service, support your account history, and meet security or legal requirements. You can request deletion of eligible account data subject to operational and legal limits.",
                    ],
                },
                {
                    title: "Sharing & Processors",
                    paragraphs: [
                        "We may share data with trusted processors who help us run the Service—such as hosting, databases, payment providers, email delivery, and analytics—under contractual confidentiality and security obligations.",
                        "We may disclose information if required by law, to protect rights and safety, or in connection with a merger, acquisition, or asset transfer where permitted.",
                    ],
                },
                {
                    title: "Cookies & Similar Technologies",
                    paragraphs: [
                        "We use essential cookies for authentication, security, and basic site function. Where used, analytics cookies help us understand how the product is used so we can improve it.",
                        "You can control cookies through your browser settings. Disabling essential cookies may prevent login or core features from working.",
                    ],
                },
                {
                    title: "Data Security",
                    paragraphs: [
                        "We apply technical and organizational measures appropriate to the risk, including access controls, encrypted transport (HTTPS), and hashed passwords.",
                        "No method of transmission or storage is completely secure. Please use a strong unique password and protect your API keys.",
                    ],
                },
                {
                    title: "Data Retention",
                    paragraphs: [
                        "We keep account and service data for as long as your account is active and as needed afterward for backups, dispute resolution, security investigations, and legal compliance.",
                        "Verification logs and cached technical results may be retained for performance, abuse prevention, and product improvement according to our operational policies.",
                    ],
                },
                {
                    title: "Your Rights",
                    paragraphs: [
                        "Depending on your location, you may have rights to access, correct, delete, or export certain personal data, or to object to or restrict certain processing.",
                        `To exercise privacy requests, contact us through the options published on the ${siteTitle} website. We may need to verify your identity before fulfilling a request.`,
                    ],
                },
                {
                    title: "International Transfers",
                    paragraphs: [
                        "Our infrastructure or processors may be located in countries other than yours. Where required, we use appropriate safeguards for cross-border transfers.",
                    ],
                },
                {
                    title: "Children",
                    paragraphs: [
                        "The Service is not directed to children under 16, and we do not knowingly collect personal information from children.",
                    ],
                },
                {
                    title: "Changes & Contact",
                    paragraphs: [
                        "We may update this Privacy Policy from time to time. The “Last updated” date at the top of this page will change when we do.",
                        `For privacy questions, contact us through the ${siteTitle} website support or contact channels.`,
                    ],
                },
            ]}
        />
    )
}
